// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SilosApi.DbContexts;

#nullable disable

namespace SilosApi.Migrations
{
    [DbContext(typeof(SilosDbContext))]
    [Migration("20250714130723_AddUniqueUsernameToUser")]
    partial class AddUniqueUsernameToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SilosApi.Entities.Silos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Bug")
                        .HasColumnType("REAL");

                    b.Property<int?>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("FreeFootage")
                        .HasColumnType("REAL");

                    b.Property<double?>("Fullness")
                        .HasColumnType("REAL");

                    b.Property<double?>("Gluten")
                        .HasColumnType("REAL");

                    b.Property<double?>("Gorchak")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("HarvestYear")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("Idk")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Nature")
                        .HasColumnType("REAL");

                    b.Property<double?>("Protein")
                        .HasColumnType("REAL");

                    b.Property<double?>("Sornaya")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalFootage")
                        .HasColumnType("REAL");

                    b.Property<double?>("Zernovaya")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Silos");
                });

            modelBuilder.Entity("SilosApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
