// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SilosApi.DbContexts;

#nullable disable

namespace SilosApi.Migrations
{
    [DbContext(typeof(SilosDbContext))]
    partial class SilosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SilosApi.Entities.Silos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Bug")
                        .HasColumnType("double precision");

                    b.Property<int?>("Class")
                        .HasColumnType("integer");

                    b.Property<double?>("FreeFootage")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fullness")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gluten")
                        .HasColumnType("double precision");

                    b.Property<double?>("Gorchak")
                        .HasColumnType("double precision");

                    b.Property<int?>("HarvestYear")
                        .HasMaxLength(4)
                        .HasColumnType("integer");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double?>("Idk")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("Nature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sornaya")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<double?>("TotalFootage")
                        .HasColumnType("double precision");

                    b.Property<double?>("Zernovaya")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Silos");
                });
#pragma warning restore 612, 618
        }
    }
}
