# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  outdated:
    runs-on: self-hosted
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Restore
      run: dotnet restore
    - name: My action
      uses: gavanlamb/.net-outdated@latest
      with:
        add-pr-comment: true
        add-check-run: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run command on remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout main;
            git pull;
            docker compose down;
            docker compose up --build -d;
            docker system prune --all --force;
